### ISSUE TITLE
Error: vkAllocateMemory failed -2

### ISSUE THREAD

**Issue by devilrus** [DaGooseYT/FrameGUI#12]
#================================================#
FrameGUI process logs for job 16243511
Video encoding arguments: "C:\Program Files (x86)\FrameGUI\vapoursynth\vspipe.exe" -c y4m "C:\Users\0\AppData\Local\FrameGUI\job-16243511\16243511.vpy" - | "C:\Program Files (x86)\FrameGUI\ffmpeg\ffmpeg.exe" -y -noautorotate -i - -c:v libx264 -crf 17 -metadata:g encoding_tool="FrameGUI v2.0.0" "C:\Users\0\AppData\Local\Temp\16243511.mkv"
Audio encoding arguments: "C:\Program Files (x86)\FrameGUI\ffmpeg\ffmpeg.exe" -y -i "C:\Users\0\AppData\Local\Temp\16243511.mkv" -i "C:\Users\0\Downloads\1.mp4" -map 0:v -c:v copy -map 1:a -c:a copy -map 1:s? -c:s mov_text -metadata:g encoding_tool="FrameGUI v2.0.0" "C:\Users\0\Desktop\1.mp4"
#================================================#

ffmpeg version n5.1-1-g6d83c5f876-20220727 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220727
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100

[0 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  bugsbn1=0  bugbilz=110  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) Iris(R) Xe Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) Iris(R) Xe Graphics]  bugsbn1=0  bugbilz=69  bugcopc=0  bugihfa=0
[1 Intel(R) Iris(R) Xe Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) Iris(R) Xe Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
vkAllocateMemory failed -2
vkAllocateMemory failed -2
Input #0, yuv4mpegpipe, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p(progressive), 4096x6216, 90 fps, 90 tbr, 90 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 00000171921a8640] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00000171921a8640] profile High, level 6.2, 4:2:0, 8-bit
[libx264 @ 00000171921a8640] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=30 lookahead_threads=5 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=17.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, matroska, to 'C:\Users\0\AppData\Local\Temp\16243511.mkv':
  Metadata:
    encoding_tool   : FrameGUI v2.0.0
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p(progressive), 4096x6216, q=2-31, 90 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.37.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A

#================================================#
End of logs
#================================================#

resolution too high?

**Comment by DaGooseYT** [comment]
No background was given on the issue... just a log file doesn't tell me anything. I'm assuming you're trying to upscale and it failed?

Anyways, this issue is clearly covered on https://encodegui.com/support:
```
This issue occurs for either one of two reasons: the GPU threads for the NCNN process is two high or your system does not have enough RAM to run the process.
```
The error message that you received had a "Help" button that linked you to that page.

You're getting this error because the upscaled resolution of 4096x6216 is too high for the encoder and so you must select a lower upscaling resolution.

You're also using an old version of FrameGUI. I don't provide support for older versions (latest free version is v2.1.0).

Closing because this issue was reported improperly (missing info) and it never required developer support from the start.
