### ISSUE TITLE
SRMD

### ISSUE THREAD

**Issue by NickPlays123** [DaGooseYT/FrameGUI#16]
When I Try To Upscale It Just Loops "intiziing assets"

**Comment by Degamisu** [comment]
Perhaps your GPU isnt supported? What is your PC's GPU?

**Comment by Degamisu** [comment]
I figured out a possible fix. Go to windows settings and change the graphics setting to high performance. there should be tutorials online that tell you how to do this. Just tested and it works. lmk if it works for you
