### ISSUE TITLE
Program.cs is missing from FrameGUI project

### ISSUE THREAD

**Issue by zydjohnHotmail** [DaGooseYT/FrameGUI#2]
Hello:
I want to build your repo from source code in Windows 10 using Visual Studio 2019 (Version 16.11.3)
I have downloaded your repo code, unzip it and open the solution in Visual Studio 2019.
But when I built it, I got error:
Error	CS2001	Source file 'D:\FrameGUI-main\FrameGUI\Program.cs' could not be found.
Can you check and make necessary update for your repo?
Thanks,

**Comment by DaGooseYT** [comment]
Hi,
I apologize for the inconvenience. The `Program.cs` file has been added in the `FrameGUI` folder here: https://github.com/DaGooseYT/FrameGUI/tree/main/FrameGUI
Please get back to me here if there are any other issues when building FrameGUI from source. Thanks.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply.  I have downloaded again the repo, unzip it and try to use Visual Studio 2019 to rebuild the solution.  But I got the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'FFLoader' could not be found (are you missing a using directive or an assembly reference?)	FrameGUI	D:\GitHubRepos\FrameGUI-main\FrameGUI\FrameGUI\Encoder.cs	7	Active

It seems other stuff is missing, please check.
I am working on Windows 10 (Version 21H1)
Thanks,

**Comment by DaGooseYT** [comment]
Nothing is truly missing. You need to build FFLoder and EncodeProg FIRST before building FrameGUI. Then, reference the built DLLs in the FrameGUI project. Sources with multiple projects don't work out of the box (for this I didn't provide the binaries in the source as it's strictly source code only so you have to build them yourself, as mentioned previously).

**Comment by zydjohnHotmail** [comment]
OK,
Thanks, it works now!
