### ISSUE TITLE
Is there a way to do batch processing?

### ISSUE THREAD

**Issue by dillfrescott** [DaGooseYT/FrameGUI#8]
I would love to be able to process more than one video without having to select and start each clip.

**Comment by DaGooseYT** [comment]
FrameGUI has reached EOL in development; no more new features or bug fixes. EncodeGUI, the successor of FrameGUI, will have batch processing support as well as a job queue. For more feature requests in EncodeGUI, you can fill out the anonymous survey here: https://docs.google.com/forms/d/13eTGsTi7RbIXqdBOYs60VGjmSRUWNCSmcjCVPouj7oM/viewform?edit_requested=true#responses
