### ISSUE TITLE
1 issue And 1 Opinion that can make FrameGui The best

### ISSUE THREAD

**Issue by Dabanngg** [DaGooseYT/FrameGUI#9]
Hello DaGooseYT i recently worked with FrameGui new version (v2.0.0) it's really impressive job you done especially for rife ai 4.6 version and using ffmpeg. I done many videos that i haved and really enjoyed with app; But Here is one real issue :
  SECENE DETECTION is really poor in this version . it's working but most scenes that camera change but it render two frames as it's a 
 scenes and make picture like a flicker for a moment each time this happen. Maybe you can change some settings and solve it.
  and a opinion : 
Please add SVP as pervious version of app and make user choose which one and like pervious version How(less artifact , balanced  , more flow) between settings . it can really be impressive to see these on FrameGui. Goodluck!

**Comment by DaGooseYT** [comment]
There are no issues with the scene change detection function. It just favors more smoothness over less scene change artefacts. There's really no "best setting" either that can be universally used across videos so some videos it will look great and others it will look bad.
As far as SVPFlow goes, that option has been added to the latest revision and is available for early access (v2.1.0).

I'm not going to add any specific options to SVPFlow though. It'll just cannabinolize the purpose of EncodeGUI. FrameGUI is designed for one-click configuration.
